version: "3.8"

services:
  frontend:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ynov_ci
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  api:
    image: python-api
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./main.py:/server/main.py
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    command: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000

volumes:
  pgdata:
